### ISSUE TITLE
Wrong link of issue on email

### ISSUE THREAD

**Issue by hanh45** [jcppkkk/redmine_mail_reminder#36] opened 2015-06-04 01:25 UTC
Hi,
The Redmine of me install with URL: http://x.x.x.x:8080/redmine
When i receipt email as report, the URL of issue wrong: http://x.x.x.x/issues/77
Please help me config to true URL in email: http://x.x.x.x:8080/redmine/issues/77
![6-4-2015 8-16-52 am](https://cloud.githubusercontent.com/assets/6047356/7975000/2642ebb8-0a93-11e5-800f-d9a71b2f1b88.jpg)

**Comment by jigmelam** [comment] 2015-06-04 01:31
Me too, the same question. Thank you!

**Comment by jcppkkk** [comment] 2015-06-04 01:48
@hanh45 Try to set redmine's host name with port, like ![image](https://cloud.githubusercontent.com/assets/84070/7975247/e32d918c-0a9e-11e5-994d-b9db7caa43ba.png)

**Comment by jigmelam** [comment] 2015-06-04 01:50
I've tried that but it not work!

**Comment by jcppkkk** [comment] 2015-06-04 02:00
@jigmelam where did you set the port number?

**Comment by jigmelam** [comment] 2015-06-04 02:41
yes, RAILS_ENV="production". I setup Redmine on Bitnami Rubystack. 
I setup port in file apps/redmine/conf/httpd-vhosts.conf
The default Redmine mail notification still work with config "Host name and path" but this reminder not update this path.
Thank!

**Comment by hanh45** [comment] 2015-06-04 02:55
Hi @jcppkkk ,
The Setting:
![setting](https://cloud.githubusercontent.com/assets/6047356/7976023/a57b5bd4-0a9f-11e5-8f41-83592789a1f9.jpg)
The command send email:
![reminder_sh](https://cloud.githubusercontent.com/assets/6047356/7976030/b44e0e40-0a9f-11e5-928a-d700c5d98934.jpg)

I don't know why if i use: bin/rake reminder:exec RAILS_ENV="production" > /dev/null 2>&1
The email is not send.

**Comment by jcppkkk** [comment] 2015-06-04 03:06
@hanh45 
0. Set redmine host without `http://` prefix
1. pull the latest code of redmine_mail_reminder master branch
2. install new required gem  `bundle install`
3. see the output of `bin/rake reminder:exec RAILS_ENV="production"`

**Comment by hanh45** [comment] 2015-06-04 04:11
Hi @jcppkkk 
I was install new redmine_mail_reminder with new code from brand.
I have project as:
![project](https://cloud.githubusercontent.com/assets/6047356/7976709/72f17d2e-0aa9-11e5-8cf6-d89ad2b1fbaa.jpg)
The issues in projects:
![issues](https://cloud.githubusercontent.com/assets/6047356/7976712/83dbe016-0aa9-11e5-91f9-0460e5c3e6ab.jpg)
Run command:
![run command](https://cloud.githubusercontent.com/assets/6047356/7976716/979698b2-0aa9-11e5-8384-6717d21537cd.jpg)
The result email:
![result email](https://cloud.githubusercontent.com/assets/6047356/7976717/9fa68fbc-0aa9-11e5-9e26-02b9796acfbd.jpg)

1. I am member and manager of all projects
2. The issues is assign to me.
3. The complete date (due date) of all issues is current day.
4. When run test with command:  bin/rake reminder:exec RAILS_ENV="production" 
    Not receipt email
5. When run test with command: bin/rake reminder:exec[test] RAILS_ENV="production"
    Receipt one email for manager, not email for member.
6. The link in email wrong (same above): i was config redmine host without http:// prefix

**Comment by Androc** [comment] 2015-06-04 05:45
> The default Redmine mail notification still work with config "Host name and path" but this reminder not update this path.
@jigmelam Do you mean that when you go to Administration->Configuration->Email notifications->Send test email it sends you an email with the right link ?

Can you do this test :
* create an issue due to tomorrow (you must fill the "due date")
* assign this issue to a user
* get the id of the user (by hovering his name on any link where his name is inside)
* run the following command, replacing the 1 in `users="1"` by the id of your user : `rake redmine:send_reminders users="1" RAILS_ENV="production"`
* you should receive an email with link to the issue you have just created, is this link correct ?

**Comment by jcppkkk** [comment] 2015-06-04 06:10
@hanh45 
> When run test with command: bin/rake reminder:exec RAILS_ENV="production"
Not receipt email

The message shows your reminder is executed recently so the execution gets ignored to prevent double-sending mails in a day. Wait for a day then it will send mails on next execution.

> When run test with command: bin/rake reminder:exec[test] RAILS_ENV="production"
Receipt one email for manager, not email for member.

What is your query setting? Do those issues show in query page of "Query for member" with your account? 

If you set reminder on parent project "Test", you should view the query from project "Test". The issues in mail should be the same as what you see in the query page.

> Expect : 1 email for manager, 3 email for member

The reminder send all result grouping by same user, so the expected result is one mail for each user. Issues of "Query for manager" and "Query for member" are both listed in one mail.

**Comment by hanh45** [comment] 2015-06-04 07:10
@jcppkkk 
>The reminder send all result grouping by same user, so the expected result is one mail for each user. 
>Issues of "Query for manager" and "Query for member" are both listed in one mail.

Yes. I receipt one email is true.

@Androc 
* I send test email: the link is true
* When i create new issue: email send to member have true link.


Can you guide me config custom query and config reminder with structure?

1. Structure
![contruct](https://cloud.githubusercontent.com/assets/6047356/7978698/a2ef0cee-0ac2-11e5-9c42-93b1f54d947e.jpg)
2. The email content expect:
**For manager**:
![email content pm](https://cloud.githubusercontent.com/assets/6047356/7978707/bb5bffee-0ac2-11e5-9f3a-45c4f749065d.jpg)
**For member1**:
![member1](https://cloud.githubusercontent.com/assets/6047356/7978710/c5829fc8-0ac2-11e5-8c96-06a4d871dd73.jpg)
**For member2**:
![member2](https://cloud.githubusercontent.com/assets/6047356/7978711/cbad5604-0ac2-11e5-9f35-f08c47a7efd6.jpg)

**Comment by Ghortes** [comment] 2015-06-25 09:23
I have the same issues, reminder give wrong links in the mail. All other mail have right link. 
Have you an idea to fix this?
The redmine host was already set like that : x.x.x.x\redmine

**Comment by BRUTEF0RCE** [comment] 2015-07-16 19:02
Same here... Any idea how to fix this?

**Comment by BRUTEF0RCE** [comment] 2015-11-21 15:41
Any idea how to solve this link problem yet?  Really, the receipe you proposed above is not solving the issue (Click on Adminstration - Settings - general - host name). Are you refering to this value to build your hyperlink in the email reminder?

**Comment by blackcomma** [comment] 2016-08-24 04:19
I try temporarily fix code
plugins/redmine_mail_reminder/app/models\mail_reminder_mailer.rb

11: h = h.to_s.gsub(%r{\/.*s}, '') unless Redmine:Utils.relative_url_root.black?

to

11: h = h.to_s.gsub(%r{\redmine/.*s}, '') unless Redmine:Utils.relative_url_root.black?

It will be work

**Comment by jcppkkk** [comment] 2018-08-07 10:17
close issue report that's too old, reopen if it reproduces

**Closed by jcppkkk** 2018-08-07 10:17 UTC
Labels: bug
